### ISSUE TITLE
Figure out why Node v10.13 fails on MacOS

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/bookshelf#126]
https://github.com/kentcdodds/bookshelf/runs/1359994006

Relevant output:

```
FAIL src/__tests__/book-screen.js (13.298 s)
  ● Console

    console.error
      { status: 404, message: 'Book not found' }

      at node_modules/react-query/lib/core/query.js:385:30

    console.error
      { status: 404, message: 'No user with the id "3672606755"' }

      at node_modules/react-query/lib/core/query.js:385:30

  ● can create a list item for the book

    TestingLibraryElementError: Unable to find an element with the role "button" and name `/mark as read/i`

    Here are the available roles:

      button:

      Name "Logout":
      <button
        class="css-105y6wg-Button-AuthenticatedApp e1baol0z3"
      />

      Name "Add to list":
      <button
        aria-label="Add to list"
        class="css-bnousp-CircleButton-TooltipButton e1baol0z0"
        data-reach-tooltip-trigger=""
      />

      --------------------------------------------------
      navigation:

      Name "":
      <nav
        class="css-17vy10h-Nav"
      />

      --------------------------------------------------
      list:

      Name "":
      <ul
        class="css-11z6h0h-Nav"
      />

      --------------------------------------------------
      listitem:

      Name "":
      <li />

      Name "":
      <li />

      Name "":
      <li />

      --------------------------------------------------
      link:

      Name "Reading List":
      <a
        class="css-14cbamv-NavLink"
        href="/list"
      />

      Name "Finished Books":
      <a
        class="css-14cbamv-NavLink"
        href="/finished"
      />

      Name "Discover":
      <a
        class="css-14cbamv-NavLink"
        href="/discover"
      />

      --------------------------------------------------
      main:

      Name "":
      <main
        class="css-12ehlsl-AuthenticatedApp"
      />

      --------------------------------------------------
      img:

      Name "iusto modi eum book cover":
      <img
        alt="iusto modi eum book cover"
        class="css-194shf0-BookScreen"
        src="http://placeimg.com/640/480"
      />

      --------------------------------------------------
      heading:

      Name "iusto modi eum":
      <h1 />

      --------------------------------------------------

    <body>
      <div>
        <div
          class="css-1pz3cpr-AuthenticatedApp"
        >
          Reymundo_Sipes71
          <button
            class="css-105y6wg-Button-AuthenticatedApp e1baol0z3"
          >
            Logout
          </button>
        </div>
        <div
          class="css-1dchfq2-AuthenticatedApp"
        >
          <div
            class="css-1bxv0zk-AuthenticatedApp"
          >
            <nav
              class="css-17vy10h-Nav"
            >
              <ul
                class="css-11z6h0h-Nav"
              >
                <li>
                  <a
                    class="css-14cbamv-NavLink"
                    href="/list"
                  >
                    Reading List
                  </a>
                </li>
                <li>
                  <a
                    class="css-14cbamv-NavLink"
                    href="/finished"
                  >
                    Finished Books
                  </a>
                </li>
                <li>
                  <a
                    class="css-14cbamv-NavLink"
                    href="/discover"
                  >
                    Discover
                  </a>
                </li>
              </ul>
            </nav>
          </div>
          <main
            class="css-12ehlsl-AuthenticatedApp"
          >
            <div>
              <div
                class="css-fkyky9-BookScreen"
              >
                <img
                  alt="iusto modi eum book cover"
                  class="css-194shf0-BookScreen"
                  src="http://placeimg.com/640/480"
                />
                <div>
                  <div
                    class="css-1tpptxu-BookScreen"
                  >
                    <div
                      class="css-y9z24n-BookScreen"
                    >
                      <h1>
                        iusto modi eum
                      </h1>
                      <div>
                        <i>
                          Kristopher Gorczany
                        </i>
                        <span
                          class="css-nn5rmi-BookScreen"
                        >
                          |
                        </span>
                        <i>
                          Cartwright - Ebert
                        </i>
                      </div>
                    </div>
                    <div
                      class="css-1etzife-BookScreen"
                    >
                      <button
                        aria-label="Add to list"
                        class="css-bnousp-CircleButton-TooltipButton e1baol0z0"
                        data-reach-tooltip-trigger=""
                      >
                        <svg
                          fill="currentColor"
                          height="1em"
                          stroke="currentColor"
                          stroke-width="0"
                          viewBox="0 0 512 512"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M256 8C119 8 8 119 8 256s111 248 248 248 248-111 248-248S393 8 256 8zm144 276c0 6.6-5.4 12-12 12h-92v92c0 6.6-5.4 12-12 12h-56c-6.6 0-12-5.4-12-12v-92h-92c-6.6 0-12-5.4-12-12v-56c0-6.6 5.4-12 12-12h92v-92c0-6.6 5.4-12 12-12h56c6.6 0 12 5.4 12 12v92h92c6.6 0 12 5.4 12 12v56z"
                          />
                        </svg>
                      </button>
                    </div>
                  </div>
                  <div
                    class="css-n6nwxy-BookScreen"
                  />
                  <br />
                  <p
                    class="css-mptbr-BookScreen"
                  >
                    Sequi est necessitatibus ab eius ea molestiae et amet iure. Repellat doloremque dolores reiciendis magnam mollitia incidunt ad assumenda expedita. Odio voluptate tempora. Voluptatem eligendi explicabo ut.
                  </p>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
    </body>

      78 | 
      79 |   expect(
    > 80 |     screen.getByRole('button', {name: /mark as read/i}),
         |            ^
      81 |   ).toBeInTheDocument()
      82 |   expect(
      83 |     screen.getByRole('button', {name: /remove from list/i}),

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:37:19)
      at args (node_modules/@testing-library/dom/dist/query-helpers.js:90:38)
      at args (node_modules/@testing-library/dom/dist/query-helpers.js:62:17)
      at getByRole (node_modules/@testing-library/dom/dist/query-helpers.js:106:19)
      at Object.<anonymous>.test (src/__tests__/book-screen.js:80:12)
```

I was able to reproduce this locally. Just didn't have time to investigate.

The easy solution is to upgrade your version of node 🤷‍♂️ But I technically support Node 10 so long as it's LTS, so I'd like to get this fixed.

**Comment by kentcdodds** [comment]
I'm guessing this was resolved thanks to: https://github.com/kentcdodds/bookshelf/commit/17ffbb46d8611e0b6932e66b5b21977c94b1d09c
