### ISSUE TITLE
Running tests gives a type error.

### ISSUE THREAD

**Issue by doingandlearning** [kentcdodds/bookshelf#28]
**What I'm running**
node v12.16.1
npm v6.13.4
Mac OS 

**What I did?**
I ran `npm run test`

**What I expected**
For the tests to run and stay in watch mode

**What happened instead?**
```
❯ npm t

> bookshelf@0.1.0 test /Users/kevin/code/bookshelf
> react-scripts test --env=jest-environment-jsdom-sixteen

TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
    at createWatcher (/Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/index.js:1052:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/index.js:1230:44)
    at /Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/index.js:517:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/Users/kevin/code/bookshelf/node_modules/jest-haste-map/build/index.js:213:9)
npm ERR! Test failed.  See above for more details.
```

**What I've tried**
Tried googling around to find relevant issues.

**Comment by kentcdodds** [comment]
Try this: https://github.com/facebook/create-react-app/issues/8677#issuecomment-606651461

**Comment by doingandlearning** [comment]
Woohoo! That worked :)
